### PR TITLE
Add 'tz' method for moment-timezone

### PR DESCRIPTION
**Pull request by runningskull**

### CODE REVIEW

**Comment by butterflyhug** [comment]
Sorry I forgot about this!

Making sure I understand things properly:  I think everything works with Moment Timezone without this PR, right?  In which case this is just a performance optimization for calling `tz` as a getter.

I'm not sure that'd be worth the side effect of possibly publishing a broken `tz` method in environments that don't have that plugin installed.  My initial instinct is that it'd be better to provide an equivalent to `unwrap` so plugins could add themselves to this array.

**Comment by butterflyhug** [comment]
@runningskull Are you still interested in this change?  I'm not opposed to merging if this solves a practical problem for you.  If I don't hear anything in the next week or two, though, I'll assume this isn't actually needed and close the PR.

Either way, thanks for the PR, and for your interest in Frozen Moment!

**Comment by manutenfruits** [comment]
Hi, I'm having this problem as well. So it works with moment-timezone out of the box for browser, when you include both scripts one after the other (because they share a global). However, when used in node.js (or webpack in my case) both frozen-moment and moment-timezone read from the same vanilla moment, which makes using frozen-moment-timezone impossible.

**Comment by manutenfruits** [comment]
Woah! I take that back. I just solved a bug that had been haunting me for months. I couldn't use frozen-moment with moment-timezone because they **depended on different versions of moment**, and each had its own instance. I'm commenting in case anyone else is in the same situation in the future!

This plugin rocks!

**Comment by butterflyhug** [comment]
@manutenfruits That's very interesting!  Do you happen to know what versions of Moment you were getting with each plugin?

Feel free to open a PR that changes our semver dependency in package.json if you think something else would play nicer with webpack as Moment continues to release new 2.x versions.  I just don't like the moment-timezone `>=` approach because I want to do proper release testing with Frozen Moment if/when Moment ever does a 3.x release.

Thanks for your helpful comments!

**Comment by manutenfruits** [comment]
you can reproduce it like this

```
"dependencies": {
    "bootstrap-daterangepicker": "^2.1.13",
    "frozen-moment": "^0.3.0",
    "moment-timezone": "^0.5.4"
  },

// Resolves to 
├─┬ bootstrap-daterangepicker@2.1.21
│ ├── jquery@2.2.4
│ └── moment@2.13.0
├─┬ frozen-moment@0.3.0
│ └── moment@2.10.6
└── moment-timezone@0.5.4
```

I end up having in my node_modues the following

```
├── bootstrap-daterangepicker
├── frozen-moment
│   ├── // frozen-moment files
│   └── node_modules
│       └── moment
│           └── // moment 2.10.6 files
├── jquery
├── moment
│   └── // moment 2.13.0 files
└── moment-timezone
```

Isn't this what peerDependencies were introduced for? Also I don't fully understand why frozen-moment gets its own moment and moment-timezone doesn't

**Comment by butterflyhug** [comment]
Thanks.  For now this seems non-urgent, so I'll plan to dig in with debugging this when I have a bit more time in a couple weeks or so.

You're right that this is the canonical problem for peerDependencies to solve.  As far as I know, though, nobody else in the Moment ecosystem is using peerDependencies for their plugins, which makes me wonder if there are still problems with that approach.  (I know peerDependencies were a bit of a mess before npm 3, and don't have much personal experience with them since the npm 3 release.)

**Comment by butterflyhug** [comment]
@manutenfruits I just opened #23 to address your issue with multiple versions of moment, although I think things may be a little fussy about what order you load the plugins in Node to get everything working as expected.  I'm going to close this now, but please open a new issue if the two plugins still aren't working together as smoothly as you'd like.

**Pull request closed without merging**
